# Define the goal

# The name of the aruco tag
string name
---
# Define the result

# Whether or not the marker was found
bool success

---
# Define the feedback message

# The pan angle
float32 pan_angle

# The tilt angle
float32 tilt_angle