name: pre-commit

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Run pre-commit checks & auto-fix
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      # Only save/apply fixes when it’s a PR
      - name: Apply fixes from pre-commit
        if: ${{ github.event_name == 'pull_request' }}
        uses: pre-commit-ci/lite-action@v1.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
